### ISSUE TITLE
Übermaß-Test failed on mobile

### ISSUE THREAD

**Issue by sennewood** [trendschau/typemill#12]
OS: Android 7
Browser: Chrome

![screenshot_2018-06-26-11-19-07-873](https://user-images.githubusercontent.com/406414/41914636-05348502-7954-11e8-907c-0dd4d0441ef1.jpeg)

**Comment by trendschau** [comment]
thank you, I excluded the file from the zip-download now. This happens while zipping the content already, but if you create a new md-file "übermaß.md", then it should work in most cases. There is no 100% guarantie, so if it does not work, then the only option is to use english letters for file-names, only.

Please check, so I can close the issue.

**Comment by sennewood** [comment]
I saw the error on typemill.net and it’s still there.

**Comment by trendschau** [comment]
Ahh, thank you, I added the correct file now on the demo-site, too, and now it is fine. It happens now and then, because there are still some manual steps in the deployment process. I have to improve the process in future. So thank you, I will close the ticket now...
