### ISSUE TITLE
Slim Application Error  

### ISSUE THREAD

**Issue by astridx** [trendschau/typemill#16]
Hello,
I installed Typemill some time ago on Ubuntu16.04 and at that time everything worked fine. I did not use Typemill in this project for other reasons.

Now I wanted to start a new attempt for a documentation. I have completely reinstalled Ubuntu 18.04 and installed lamp. Then I cloned this repo into the document root of apache and run `composer update`.
But, when I  open `http://localhost/typemill/` I see only an error:

> Slim Application Error - A website error has occurred. Sorry for the temporary inconvenience.

It's probably because I did not properly configure something or I did not set the right permissions. Can you help me?

**Comment by trendschau** [comment]
Hi Astrid, 

can you please open the file "settings.yaml" in the folder "settings" and then add this as the first line: 

`displayErrorDetails: true`

This will turn on the detailed error reporting of the Slim Framework. Can you please post the error details here, so that I can fix it?

Thank you!
Sebastian

**Comment by astridx** [comment]
Hello Sebastian,

thank you for your feedback.

There was no `settings.yaml`, because I could not start the setup process.

But I realized, that I could start this setup process via 
`http://localhost/typemill/index.php/setup`
so I add the `index.php`.

After that I could 
- create a user, 
- was redirected to `http://localhost/typemill/index.php/setup/welcome`
- and the file `settings.yaml` was created.

I added 
`displayErrorDetails: true`
as first line to the file `settings.yaml`.

If I open http://localhost/typemill/index.php/typemill
![bildschirmfoto von 2018-10-12 10-15-04](https://user-images.githubusercontent.com/9974686/46856906-f7a9e680-ce07-11e8-864c-16ae90ece29c.png)

If I open http://localhost/typemill/typemill
![bildschirmfoto von 2018-10-12 10-17-16](https://user-images.githubusercontent.com/9974686/46856940-07292f80-ce08-11e8-9942-2aaca35b8252.png)

**Comment by trendschau** [comment]
Hi Astrid, 

I tested the GitHub-Version on my localhost again and it works well, so I suppose that some system requirements are missing on your ubuntu installation. I have no experience with ubuntu, but can you check: 

* that htaccess files are allowed on your system
* that mod_rewrite module is activated on your system. 

For me, the errors above look like routing and redirect problems, and these problems appear if htaccess or mod_rewrite is not active. The htaccess strips out the `index.php` part from the url. After that the routing logic of Typemill searches for urls without `index.php` in a directory of all typemill-content-pages. With `index.php` in the url, Typemill does not find any page and that is why you get the error. 

I will think about a programmatic solution for this in the next version of Typemill.

Sorry that I cannot help with ubuntu, but I am sure that there are helpful tutorials with htaccess and mod_rewrite for ubuntu out there.

**Comment by astridx** [comment]
Thank you very much. Now it works.

The problem was my missing Apache knowledge. I thought enabling mod_rewrite is enough. But I had to add the text

```
    <Directory /var/www/html>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>
```

into the section `<VirtualHost *:80>` of the file `/etc/apache2/sites-available/000-default.conf`

with `sudo gedit /etc/apache2/sites-available/000-default.conf`

**Comment by trendschau** [comment]
Hi Astrid, 

by the way: thank you for sharing this solution, I will add it to the setup-documentation because it seems to be a common problem for ubuntu/linux users....
