### ISSUE TITLE
Cannot install Typemill

### ISSUE THREAD

**Issue by xohudson** [trendschau/typemill#17]
Hi Sebastian,

first thanks for coding Typemill. I really want to use it, but i have problems with installation by https://typemill.net/getting-started/installation .. I´ve no SETUP no Buttons on the Page does work at so on. 

best regards 

Stephan

**Comment by trendschau** [comment]
Hi Stephan, 

can you give me some more details? If buttons and links on the page do not work (on your local machine?), than I am pretty sure that some requirements are not given in your environment. E.g. apache with mod_rewrite is required. Maybe this thread (about Ubuntu) will help: https://github.com/trendschau/typemill/issues/16

If you do not get any error message, then please go to -> settings -> settings.yaml and add a new line line: `displayErrorDetails: true` for your local development. This will turn on the detailed error reporting of Slim.

Let me know if this helps...

Best regards
Sebastian

**Comment by xohudson** [comment]
Hi Sebastian

mod_rewrite is active. I installed via `GIT` and `compose update` 

at this time i see 4 Buttons . (Start , Setup , Write Content and Get Help) but none of this links are working.

settings -> setting.yaml are not there.

see here : 
![image](https://user-images.githubusercontent.com/38777167/48126024-7156b800-e280-11e8-937c-07a06baec1eb.png)

![image](https://user-images.githubusercontent.com/38777167/48126056-86cbe200-e280-11e8-942d-cd76f314a1ef.png)

**Comment by trendschau** [comment]
what exactly means "not working"? What happens if you click on "setup"?

Do you have access to an url with `index.php` like `http://localhost/typemill/index.php/setup` or wherever your typemill installation lives?

You can also try to create the file `settings.yaml` manually with just one line `displayErrorDetails: true` and place it into the settings folder. Not sure in your environment, but it might work, too and show the errors.

I am back in the evening and will check it again.

**Comment by xohudson** [comment]
it means : 

![image](https://user-images.githubusercontent.com/38777167/48127746-c5fc3200-e284-11e8-94c6-1074ae869e02.png)

an requests on http://192.168.20.252/typemill/typemill/index.php/setup

![image](https://user-images.githubusercontent.com/38777167/48127838-f80d9400-e284-11e8-81b0-40b93037c16f.png)

I will check this ASAP :+1: 

> You can also try to create the file settings.yaml manually with just one line displayErrorDetails: true and place it into the settings folder. Not sure in your environment, but it might work, too and show the errors.

**Comment by xohudson** [comment]
result is the Setup Button is gone away but pressing Start is gone to "nirvana 404"

**Comment by xohudson** [comment]
> result is the Setup Button is gone away but pressing Start is gone to "nirvana 404"

In XAMPP it will run. What du i make wrong ???

**Comment by trendschau** [comment]
Hi Stephan, 

if you want to get help, you should try to provide exact error descriptions. If it works in XAMPP, where does it NOT work? Which environement do you use? Did you read issue #16 ? because I am pretty sure that it is the same issue with your apache configuration. I can see that you use a debian-linux-system and in #16 a user solved this error with ubuntu, I suppose that it is the same error, so please test if the workaround in #16 works ...

**Comment by xohudson** [comment]
Hi Sebastian,

I wnat to run it on Debian 9 with Apache2 . So that i can publish my work to others per official link and so on . 

The run at XAMPP is fine but not the Finish.

I will test #16 asap and notice what happen.

**Comment by trendschau** [comment]
Hi Stephan, 

please let me know if the described solution helped with you problem. I will add that to the documentation then. I found a longer description for the solution on digitalocean here: https://www.digitalocean.com/community/tutorials/how-to-rewrite-urls-with-mod_rewrite-for-apache-on-ubuntu-16-04

**Comment by trendschau** [comment]
and for Debian 9 it looks pretty similar: https://www.digitalocean.com/community/tutorials/how-to-rewrite-urls-with-mod-rewrite-for-apache-on-debian-9

**Comment by xohudson** [comment]
Hi i´ve tested and yes i can move to the Content now . But Setup and /tm/login and so on is not working. so i cannot create Content. It´s Crazy but i don´t now what is missing.

> and for Debian 9 it looks pretty similar: https://www.digitalocean.com/community/tutorials/how-to-rewrite-urls-with-mod-rewrite-for-apache-on-debian-9

of course @Step 3 — Configuring URL Rewrites 

i don´t now what todo.

**Comment by xohudson** [comment]
So i must say : IT WORKS!

the resolution : 

I deinstalled Apache2 , PHP5.6 PHP7.1 & PHP7.2 incl all configuration Files.

then fresh install of Apache2 , PHP5.6 & PHP7.2

enable PHP7.2

`$ sudo a2enmod php7.2`

write into the section `<VirtualHost *:80>` of the file `/etc/apache2/sites-available/000-default.conf` by using nano.

```
    <Directory /var/www/html>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>

```

then enable mod_rewrite in Apache2 

`$ sudo a2enmod rewrite`

This would be all to install or copy Typemill on webhost Debian 9 & Apache2

Sorry for my "corructed" Apache2 installation but now it works.

**Comment by trendschau** [comment]
Glad to hear that and thank you for sharing your solution!
