### ISSUE TITLE
Any chance of [TOC]

### ISSUE THREAD

**Issue by carstenwm** [trendschau/typemill#2]
Thank you for Typemill, love the simplicity and ease on the eyes
Any chance of having GitHub Flavored Markdown in there, would like to use [TOC]

//Carsten, Denmark

**Comment by trendschau** [comment]
Hi Carsten, I use the Parsedown library and the docs say, that it supports GitHub Flavored Markdown: https://github.com/erusev/parsedown Did you have any trouble with special formats?

**Comment by carstenwm** [comment]
Thanks, Sebastian. I think what I essentially were interested in was actually being able to print/pdf' all content files from the one site into one file / print - the TOC thing could be one step in that direction for me although I love your very fast working (after uploads) content menu.

**Comment by moritzfl** [comment]
@carstenwm I agree with that - some kind of possibility for fast and easy pdf-conversion would come in quite handy.
After a slight misuse of typemill to create my own website, I am currently looking at it with the intended purpose in mind - I need to be able to quickly output pdf/paper though.

**Comment by trendschau** [comment]
Yes, PDF-conversion was planned for a future version of typemill, too, but this will probably some more work. I will have a look into it.

**Comment by trendschau** [comment]
[TOC] has been implemented in version 1.0.5. PDF creation will be part of a later version, actually some technical enhancements have first prio.

Have fun with the TOC-Tag
