### ISSUE TITLE
Docker with Proxy - OK - but SSL?

### ISSUE THREAD

**Issue by ghost** [trendschau/typemill#396]
I try to use typemill with a reverse proxy with SSL. It works good with http. It works so far with HTTPS, as the source of the side is delivered, but not the assessments. I recognized, that there is a rewrite-rule to several paths to index.php. 

Maybe this is a barrier for the reverse proxy ? Or is there somewhere a setting I have to adjust?

**Comment by nudeldudel** [comment]
Yes, of course I did first... 😁

trendschau ***@***.***> schrieb am Do., 13. Apr. 2023, 19:12:

**Comment by trendschau** [comment]
You can try if it works now with Typemill Version 2.1.1. 

Not super sure about your setup, the Docker image does not support SSL, not sure if you have docker behind a ssl-proxy? Never tried that, not sure if it works.

**Comment by trendschau** [comment]
I tested it with version 2.3.0. It should work, but there are many different configurations depending on your environment. In version 2.3.0 you can force an base-url with something like "https://myproxyurl.io" and that should work (it worked for me and for a client). 

Let me know if this helps.
