### ISSUE TITLE
Folders as titles

### ISSUE THREAD

**Issue by Ranxeon** [trendschau/typemill#409]
Is there a simple way to use Folders as simple titles (kind of like a category title) without link and excluded from the breadcrumbs? The first part I have managed and it works great but when it comes to the breadcrumbs I just can't figure out how to exclude the folder link and have the prev/next buttons to only jump to items. Any help would be very much appreciated.

![folder](https://github.com/typemill/typemill/assets/142297619/088ede66-b8ea-4696-806d-3d295b0db613)

**Comment by trendschau** [comment]
I suppose that is only possible if you change the core-code. For the breadcrumb you can exclude the base-folder (or all folders), this information should be part of the breadcrumb-item data so you can probably change it in the partial of the theme. The jump-forward/backward button has a very complex logic and I don't think that you can change that easily (but did not dig into it). Of ypi simply erase it, then you could realise it mostly with changing the theme logic and not touching typemill core code.

**Comment by trendschau** [comment]
Thanks again for your suggestion. So Typemill core has a different logic right now and this won't change in near future. This might be a good case for a fork, so I will close this ticket for now.
