### ISSUE TITLE
Changing the slug of a blog/page?

### ISSUE THREAD

**Issue by thopanX** [trendschau/typemill#410]
Can anybody enlighten me on what the prerequisites are for successfully changing a slug? It sometimes worksm and sometimes it doesn't for me. Can't really replicate this reliably.

**Comment by trendschau** [comment]
I did not had any problems yet and it is hard to fix without replication. Do you see error messages?

**Comment by thopanX** [comment]
I sometimes get a 404 after submitting the new slug, no other messages. I can't reliably replicate myself, sadly 

Using latest Firefox on Linux, latest Typemill. Will gladly provide more unfo, if you need more.

Am 8. September 2023 14:14:17 MESZ schrieb trendschau ***@***.***>:

**Comment by trendschau** [comment]
I hope that this issue is gone now with version 2.X (2.3.0 is out now). I could not reproduce it, if you still face this problem, please reopen the ticket with more infos how to reproduce it. 

thank you very much!
