### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by ashraf21c** [trendschau/typemill#414]
Hello, any proven RTLing methods that work with Typemill?
I tried some (based on suggestions I found in some sites) but they don`t work.

**Comment by trendschau** [comment]
sorry for late reply, Typemill does not support rtl out of the box. You can experiment with rtl-style in html-tag like this: 

`<html lang="en" style="direction:rtl">`

But I doubt that this will work in detail. Since I am not familiar with rtl-languages, it is hard to test for me.

**Comment by ashraf21c** [comment]
Thank you for your reply.
I already tried changing it, using suggested code as well as other ways,
but no solution worked.


في الأربعاء، ٢٥ أكتوبر ٢٠٢٣, ٥:٣٨ م trendschau ***@***.***>
كتب:

**Comment by svanlaere** [comment]
Have you tried these attributes in the html tag?

dir="rtl" lang="ar"

More information:
https://www.w3.org/International/questions/qa-html-dir

**Comment by ashraf21c** [comment]
In Custom CSS plugin: 
`.element { direction: rtl; }`

No change

**Comment by ashraf21c** [comment]
In posts/ pages:  ((I even tried editing the files using FTP and Notepad++))
The following codes - no change

**Comment by ashraf21c** [comment]
`<div dir="rtl">some Arabic text</div>`

**Comment by ashraf21c** [comment]
`<html lang="ar" style="direction:rtl">`

**Comment by ashraf21c** [comment]
'<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
<meta charset="utf-8">'

The above is doctype, with dir, lang and charset set. It`s not appearing here.

**Comment by ashraf21c** [comment]
`<html dir="rtl">text for testing</html>`

**Comment by ashraf21c** [comment]
`<div dir="rtl" align="right">
text for testing
</div>`

The above is div dir rtl align right

**Comment by ashraf21c** [comment]
`<div dir="rtl">
text for testing
  </div>`

The above is div dir rtl

**Comment by ashraf21c** [comment]
Given the fact Typemill is using Markdown,
this is the only MarkDown editor that succesffuly works for RTL, and does not require any codes.
I hope it can be included into Typemill.

https://github.com/dariubs/rtlmd

To see it in action (web based): https://rtlmd.codecast.ir/

**Comment by trendschau** [comment]
thank you for the hint, this requires quite a lot of work and I am not able to test it, so it is not on the roadmap right now. Maybe this is a good case for a fork. I will keep it in mind, but the roadmap for the next 12-24 month is pretty full.
