### ISSUE TITLE
[2.0.1] New posts in a single-account install don't pull author name from settings

### ISSUE THREAD

**Issue by thopanX** [trendschau/typemill#422]
More info needed?

**Comment by trendschau** [comment]
Checking it right now. I am not sure if the author from the settings is a good idea. If there are more than one authors, then there is no way to check if the current user is the same as the author from the settings or not, so it is unclear what to use in those cases. I think it is better to check the current user and use the first and last name from the user profile.

So I will change it the following way: 

* In the system settings I will rename the "author" to "website owner". I think he is only used for the copyright line. 
* In the meta for each page I will try to get the first and last name of the current user and use that for the author line.

**Comment by trendschau** [comment]
fixed and published/pushed

**Comment by thopanX** [comment]
Confirmed that it works here now. Thanks!
