### ISSUE TITLE
Tabs for 'Content' and 'Meta' are no longer displayed in Version 2.0.3

### ISSUE THREAD

**Issue by robs-fotoalbum** [trendschau/typemill#433]
When I open the editor, the tabs are shown for a second or so Then they are gone.
![grafik](https://github.com/typemill/typemill/assets/111909427/4e2f7f86-7838-4eab-a32e-250b6ae69bb2)

Version 1:
![grafik](https://github.com/typemill/typemill/assets/111909427/7d0be3e3-50ca-4fad-96a3-6e0b31efe67d)

Any idea what happened here? I migrated the respective site from V1 to V2. Had some trouble during migration, the tabs very visible afterwards, today they are gone.

**Comment by trendschau** [comment]
hard to say from the distance but it looks like a Vue error to me. Can you activate the developer tools in the browser and check if you see any errors in the tabs "console" or "network" of the developer tools?

**Comment by robs-fotoalbum** [comment]
Here is what I got from the Firefox console:
<img width="1427" alt="grafik" src="https://github.com/typemill/typemill/assets/111909427/1293bdb8-2164-46a7-9d02-b4b9e1339c20">

**Comment by trendschau** [comment]
Ok, I see the error but I cannot reproduce it right now. Please fix your installation and upgrade first. If the error still exits, I will check it again and try to reproduce.

**Comment by robs-fotoalbum** [comment]
This can be closed as my newly setup installation works fine now 😊

**Comment by trendschau** [comment]
Great, congratulations and I am happy to hear that!
