### ISSUE TITLE
BUG: Can't open the themes page after activating a new theme

### ISSUE THREAD

**Issue by azmy60** [trendschau/typemill#436]
Hi, I'm just trying out typemill. And I'm finding an error when trying to add a new theme.

Steps to replicate:
1. Clone the https://github.com/typemill-resources/dev to the `themes` folder
2. Open the `localhost/tm/themes`
3. Activate the `dev` theme
4. Refresh the page
5. The error that shows up:

```
Slim Application Error
The application could not run because of the following error:

Details
Type: TypeError
Code: 0
Message: Cannot access offset of type string on string
File: ... typemill-2.1.1/system/typemill/Models/Extension.php
Line: 59
```

Removing the theme from the `themes` folder doesn't fix the error. I had to clone a new repo to fix it. And it only happens in `localhost/tm/themes`.

I tried making a new theme from copy pasting the default theme (cyanine). I also tried following the [docs](https://typemill.net/theme-developers/quick-start) but still had the same error.

I used version 2.1.1 from the download page and through `git clone`. I haven't tried the previous versions yet, but I'll bring you some updates if I find something.

**Comment by trendschau** [comment]
Sorry for the confusion, I did not know that the typemill-resources repos are still linked, where did you find them? 

The repos are not updated for Typemill Version 2 yet, and the old themes do not work. I am updating the documentation step by step.

The only valid source for themes and plugins are the official websites now: https:///themes.typemill.net and https://plugins.typemill.net.

**Comment by Benovitch83** [comment]
In the meantime, I'd like to point out that the zip file for the "About Me" theme doesn't seem to be working at the moment (extraction error). Thanks for all your hard work migrating to v2!

**Comment by trendschau** [comment]
Yes, you are right, I will update the zip asap, my failure...

**Comment by trendschau** [comment]
ok, thank you again for reporting, I had the same strange error too, today. Will try to fix. Download of themes work again. I suppose that an internal error was thrown that corrupted the zip-download.

**Comment by Benovitch83** [comment]
Thank you. It works like charm now!

**Comment by trendschau** [comment]
glad to hear that!
