### ISSUE TITLE
Spelling mistakes in German

### ISSUE THREAD

**Issue by mkduew** [trendschau/typemill#445]
while editing an image. the class "recht" should be "rechts"

<img width="817" alt="class" src="https://github.com/typemill/typemill/assets/17476152/35de9239-fc21-4a3c-a487-d3b656e0be99">

under System / Media. it should be "konvertieren" not "konvertrieren"

<img width="798" alt="konvertieren" src="https://github.com/typemill/typemill/assets/17476152/1d46bab4-d134-4628-8ebf-cd47d7a801dc">

Typemill version 2.2.1

**Comment by trendschau** [comment]
fixed in 2.3.0
