### ISSUE TITLE
Problems with the deletion of blocks (bug!)

### ISSUE THREAD

**Issue by mkduew** [trendschau/typemill#447]
If you are in edit mode in a block and then delete this block, there are display errors. The wrong content is displayed and the wrong block is deleted.

Please see the screen recording:

https://github.com/typemill/typemill/assets/17476152/906f83d4-7d8f-460d-80be-2717761ee2ab

Typemill version 2.2.1

**Comment by trendschau** [comment]
fixed in upcomming version 2.3.0

**Comment by trendschau** [comment]
2.3.0 is out now.
