### ISSUE TITLE
missing translation in German "add a file" / "add a folder"

### ISSUE THREAD

**Issue by mkduew** [trendschau/typemill#449]
the hint of the buttons is missing a translation. see screenshots:

<img width="327" alt="add_a_file" src="https://github.com/typemill/typemill/assets/17476152/a64bd00f-7015-47a3-aecf-4f9cdac4b967">

<img width="361" alt="add_a_folder" src="https://github.com/typemill/typemill/assets/17476152/14be7d7d-3cc7-47c9-af8b-d1b87f9889f8">

**Comment by trendschau** [comment]
fixed in 2.3.0
