### ISSUE TITLE
missing translation in German for expand and collapse navigation

### ISSUE THREAD

**Issue by mkduew** [trendschau/typemill#451]
see screenshots:

<img width="313" alt="expand" src="https://github.com/typemill/typemill/assets/17476152/f4d61128-9c2c-4bbb-902c-2e9c770b8c70">

<img width="322" alt="collapse" src="https://github.com/typemill/typemill/assets/17476152/f8656ac2-c76d-4731-8117-bbdec618f42e">

**Comment by trendschau** [comment]
You can add labels for these buttons in the theme settings. Translations for themes and plugins with translation files are not implemented yet, but on the roadmap for later.
