### ISSUE TITLE
typo in login page (German)

### ISSUE THREAD

**Issue by mkduew** [trendschau/typemill#457]
just one exclamation mark, not two. there is one in the translation. must be removed. see screenshots:

<img width="633" alt="Bildschirmfoto 2024-03-07 um 20 15 38" src="https://github.com/typemill/typemill/assets/17476152/245997e2-8635-4541-9cc4-d3b59f23af01">

<img width="1205" alt="Bildschirmfoto 2024-03-07 um 20 15 50" src="https://github.com/typemill/typemill/assets/17476152/8399cb02-9d20-4588-8dc3-d13fb35b32db">

**Comment by trendschau** [comment]
fixed in 2.3.0
