### ISSUE TITLE
Personal Theme not working

### ISSUE THREAD

**Issue by elamp75** [trendschau/typemill#458]
Hello,

I have an issue with the "Personal Theme".

The download page says it's version 2.0.0, whereas the backend says I'm using version 1.3.0, and the frontend only shows one line: "Hi from asset class, Tachyons not available in Typemill v2". The other themes work fine.

Am I doing something wrong or is this a deprecated download file?

**Comment by trendschau** [comment]
Thank you for the hint, it was the wrong zip-file. I updated it now, please download and try again.

**Comment by elamp75** [comment]
Problem solved, thank you!
