### ISSUE TITLE
No documentation concerning "public_key.pem".

### ISSUE THREAD

**Issue by nicholasfechner** [trendschau/typemill#459]
The admin keeps asking me to "Please check if there is a readable file public_key.pem in your settings folder." But there is no mention of any need for key in the documentation (or anywhere else on Google).

What kind of a certificate is needed here or what is it used for?

**Comment by nicholasfechner** [comment]
Addition: I'm using the docker build deployment.

From looking at the source code, this seems to be only needed for licensing. So simply ignore it for unlicensed use?

**Comment by trendschau** [comment]
Hi Nicholas, yes, it is only needed for the license. Where do you see this notification in the admin area? It should only appear on the license page. I will add it to the documentation asap

**Comment by trendschau** [comment]
Ah, ok I see, it is in the system settings, I will fix it, so that it only appears on the license page. 

Anyway, you can ignore it, it is only used to verify your license data (if there any) and to communicate with the license server. If you have no license, or if you do not try to activate licenses plugins, then it does nothing.

**Comment by nicholasfechner** [comment]
Thanks 👍, a short note in the docs might help too.

**Comment by trendschau** [comment]
Sorry, I have to correct myself. The public_key.pem is also used to "authenticate" calls for the version-check in Version 2 of Typemill, so it is required for this feature, too. Not critical either, but if you want to get update notifications, then you should add the file into the settings folder. I will add it to the documentation and to the error message. The pem-file is missing in your installation and probably in the docker-setup? I did not test this detail yet.

**Comment by trendschau** [comment]
I added it to the documentation: https://typemill.net/getting-started/installation#h-the-file-public-keypem
