### ISSUE TITLE
Problem updating a user's password as an admin

### ISSUE THREAD

**Issue by mkduew** [trendschau/typemill#461]
as an admin, how can I change a user's password, without knowing his current password ("Aktuelles Passwort"). So current password doesn't make any sense, if I edit a user as an admin.

<img width="848" alt="Bildschirmfoto 2024-03-25 um 12 10 42" src="https://github.com/typemill/typemill/assets/17476152/67b0b4ca-fe2d-4f2c-9ad5-cb9846840278">

**Comment by mkduew** [comment]
If I only edit the new password ("Neues Passwort") and press "save" ("Speichern"), Typemill says "Nutzer wurde aktualisiert". But changing the password did not work. There is also no error message.

**Comment by trendschau** [comment]
Yes, thank you, has been reported from other users already and i will fix it with the next release

**Comment by trendschau** [comment]
I refactored it with version 2.3.3.  If a user changes his password, he must add the valid old password and a new password. The admin can add only a new password without old password now.
