### ISSUE TITLE
Media links are not shown in 2.3.3. (and 2.3.2)

### ISSUE THREAD

**Issue by robs-fotoalbum** [trendschau/typemill#467]
I was not very active with my site the last months and just noticed that links to photos are no longer shown as in previous versions. This might be even an issue from 2.0. An example of my site is here: https://xprssn.st/deutsch/projekte/london/2013#h-2013
When you switch to reading mode, the photos are shown. Same issue in Firefox and Safari. With Brave similar - reader mode doesn't show photos here. Other browser not tested. MacOS and iOS.

**Comment by robs-fotoalbum** [comment]
I checked after the update to 2.4.1. - same issue. The Markdown code has not changed on my pages, if I check it with e.g. Typora everything is going to be displayed.

**Comment by trendschau** [comment]
Yes, sorry, I did not had the time to go into it but checked it quickly now. 

You include your images from a different domain, your domain is https://xprssn.st and the domain for images is https://fotogalerie.ws

Typemill version 2 is stricter with security and does not allow content from other domains (it is called content security policy csp). You can simply add those external domains to the whitelist. Go to system, open the tab "developer" and check the input field for "csp". There you can enter the domain for your images and then it should work. (See screenshot).

You can also disable csp completely, but this will be less secure then. I will add this to the documentation somewhere more prominently....

![Unbenannt](https://github.com/typemill/typemill/assets/2714547/0404c166-0e7f-49fc-a6d1-ae3aca5ac4b2)

**Comment by robs-fotoalbum** [comment]
Thank you, that seems to be the point, yes, probably it is since 2.0 and just didn't realise it earlier. It works fine now :-)

**Comment by k1ngf15h3r** [comment]
> Yes, sorry, I did not had the time to go into it but checked it quickly now.
> 
> You include your images from a different domain, your domain is https://xprssn.st and the domain for images is https://fotogalerie.ws
> 
> Typemill version 2 is stricter with security and does not allow content from other domains (it is called content security policy csp). You can simply add those external domains to the whitelist. Go to system, open the tab "developer" and check the input field for "csp". There you can enter the domain for your images and then it should work. (See screenshot).
> 
> You can also disable csp completely, but this will be less secure then. I will add this to the documentation somewhere more prominently....
> 
> ![Unbenannt](https://github.com/typemill/typemill/assets/2714547/0404c166-0e7f-49fc-a6d1-ae3aca5ac4b2)

Unable to resolve the issue with this hint because I am unable to access this site when hosting with portainer and traefik. The system pages is blank and I have no option to access this - there must be a better default solutions like ENV Vars or predfined CSP whitelist.
