### ISSUE TITLE
After upgrade to V2.4.1. from V1 - cannot access. ../ tm/content/visual

### ISSUE THREAD

**Issue by robs-fotoalbum** [trendschau/typemill#470]
I had trouble to upgrade an older installation t the latest version. The fresh 2.4.1. showed a setup screen without the known style sheet and I was not able to access the administration site. The frontend was working. I was then shifting everything to local host and rebuild the site with the new version. There everything worked fine. Shifting it back to the web the same issue. Error 500 and too many redirects. What can I do to solve this problem?

**Comment by xprssnst** [comment]
Probably some .htaccess issue - in the upgrade guide this is mentioned:

.htaccess: Do NOT copy the old htaccess-file, it will not work with version 2. If you had any individual settings in your htaccess, then copy them manually into the new htaccess-file.

But there was no .htaccess file in the ZIP folder of 2.4.1.

**Comment by robs-fotoalbum** [comment]
Found it - cookie error. Deleted cookies and now it works fine. Could be a point for the upgrade guide.
