### ISSUE TITLE
Urlinfo scheme is "http" when website is behind Cloudflare

### ISSUE THREAD

**Issue by fujaru** [trendschau/typemill#478]
When accessing the website with "https" but the website itself is hosted behind a proxy or load balancer such as Cloudflare, a lot of buttons such as create new content/folder, publish etc don't work. By opening browser dev tools I found ajax requests are sent with "http" instead of "https" and so the browser blocked it.

A likely reason is because a connection between client to the proxy server is done with https, but connection between the proxy server and the actual web server is done with http.

I could make it work by modifying system.php:137 to check for HTTP_X_FORWARDED_PROTO header.
```
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO'])) {
	$uri = $uri->withScheme($_SERVER['HTTP_X_FORWARDED_PROTO']);
}
$urlinfo 				= Urlinfo::getUrlInfo($basepath, $uri, $settings);
```

Based on these articles, this header is added by proxy servers to indicate what protocol is used between the client and proxy server.
https://developers.cloudflare.com/fundamentals/reference/http-request-headers/#x-forwarded-proto
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto

**Comment by trendschau** [comment]
Yes, did you try the proxy-detection in the developer tab of the system settings? There is a proxy detection and if it does not work in complex environments you can also force an url/schema

**Comment by fujaru** [comment]
Thank you for pointing out the settings! 
I tested enabling proxy as well as setting a base-url under the developer tab and these options didn't work unfortunately. When editing a content for example, clicking Publish button showed the ajax request was still sent to the same url with http (not the one that was set in base-url).

**Comment by trendschau** [comment]
Thank you for the Information, that is strange, I only tested it with a local proxy but some clients use it successfully. I will check if I can test it with cloudflare somehow.

**Comment by trendschau** [comment]
Sorry, just published a new release, I will have a look in the next days...

**Comment by trendschau** [comment]
Yes, i see the problem, will be fixed with release 2.6.0

**Comment by trendschau** [comment]
please try with version 2.6.0 now, I hope it works, let me know if you still have issues.

**Comment by fujaru** [comment]
Thank you! Sorry I was not being able to test it soon enough.. Tested with 2.10.0 and it works flawlessly with Cloudflare.
