### ISSUE TITLE
Password length (5-40)

### ISSUE THREAD

**Issue by joho1968** [trendschau/typemill#481]
Curious as to why is there a set password length constraint of 5-40 characters? :thinking: 

To have a minimum length, yes absolutely. To have a maximum length, yeah I get that too, but 40?

I often use password generators that'll create 64-256 character passwords.

I don't see how this would be an issue to support lengths up to ... some arbitrary number ... 512? 1024? characters. It's not stored as is anyway, I hope :wink:

**Comment by trendschau** [comment]
5-40 is just ... random, generally limited to prevent HTTP POST DoS, payload attacks and similar, so I can adjust this number to 256 in next release for example. No, it is not stored of course, it is encrypted with \password_hash($password, PASSWORD_DEFAULT, ['cost' => 10]);

**Comment by joho1968** [comment]
I don't think you need to worry about setting a limit to avoid DoS, etc; any site that cannot handle at least 1024 bytes as a POST payload, or otherwise, is probably misconfigured at the server level, and that is not your concern/problem.

**Comment by trendschau** [comment]
added 256 in release 2.6.0.
