### ISSUE TITLE
google adsense script wird nicht ausgeführt

### ISSUE THREAD

**Issue by fnow54** [trendschau/typemill#486]
Guten Tag, ich möchte gern adsense auf meiner Webseite energytools.de einsetzen. Alle Voraussetzungen sind laut google adsense erfüllt, aber die Ausführung des Scriptes im Headbereich wird verweigert mit dem Hinweis aus CSP. 

Ich habe verschiedene Varianten des CSP eingefügt, z.B. <meta http-equiv="Content-Security-Policy" content="script-src-elem 'self' https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js? ... " /> aber ich erhalte im Test auf der search console immer eine oder mehrere Fehlermeldungen mit folgenden Inhalt: 

Refused to load the script 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1885638841547169' because it violates the following Content Security Policy directive: "default-src 'unsafe-inline' 'unsafe-eval' 'self' data: *.youtube-nocookie.com *.youtube.com". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

Wo könnte den diese Direktive:  default-src 'unsafe-inline' 'unsafe-eval' 'self' data: *.youtube-nocookie.com *.youtube.com
herkommen, in den Typemill_Dateien habe ich dazu nichts gefunden. Als Browser habe ich opera und chrome benutzt, bei beiden die gleiche Fehlermeldung.

Ich bin 71 und recht ratlos und verstehe das nicht mehr so ganz. Kann jemand helfen? Danke!

**Comment by trendschau** [comment]
Es gibt zwei Möglichkeiten: 

* Man kann CSP komplett deaktivieren, und zwar unter -> System -> Developer/Entwickler und dort die Checkbox für die Deaktivierung der CSP-Header. 
* Unter demselben Tab kann man optional auch URLs einfügen, die für CSP freigeschaltet werden sollen. 

Ich würde empfehlen, zunächst die URL zum CSP hinzuzufügen und wenn das nicht funktioniert, dann CSP komplett zu deaktivieren. Grundätzlich ist CSP eine sehr sinnvolle Maßnahme um die Sicherheit einer Seite zu erhöhen. 

![Unbenannt](https://github.com/typemill/typemill/assets/2714547/9b3e1f6e-feeb-4f26-85a1-353abfcdc08a)

Wenn Adsence per Plugin integriert wird (was der beste Weg wäre), dann können die URLs auch über das Plugin für CSP freigeschaltet werden. Leider noch nicht in der Dokumentation enthalten aber man kann sich am Code des Analytics-Plugins orientieren: https://plugins.typemill.net/analytics

**Comment by trendschau** [comment]
Hatte der Hinweis geholfen und kann ich das Ticket schließen?
