### ISSUE TITLE
Slim Application Error - Bettersearch Plugin asks for License

### ISSUE THREAD

**Issue by robs-fotoalbum** [trendschau/typemill#500]
Hello, just got a maker license yesterday and tried the Bettersearch plugin today, but this won't work. Any idea where the error is created? When I remove the plugin, the site runs fine again. The license is entered correctly as I use the new Guide theme.

**Comment by trendschau** [comment]
Good morning, I am sorry to hear that, can you provide some more information so I can try to fix it? 

* Do you see your license data in the menu point "license"?
* From the title I see that there is a slim application error. Could you send me the whole message? Here is how you can do it: 
  * go to system setting
  * click on the tab "developer"
  * activate the first checkbox "Display Errors"
* Then you can reproduce the error again and see the whole error message. 

With that error message I can try to help or fix it. I can see that your license has been activated correctly. 

![Screenshot 2024-12-17 at 10-59-15 System settings](https://github.com/user-attachments/assets/78c924f9-a1cd-44c5-b21d-910a19ab189f)

**Comment by robs-fotoalbum** [comment]
Hello, here I'm back with the full message - hope that helps to analyse it.
Cheers
Rob

Slim Application Error
The application could not run because of the following error:

Details

Type: FastRoute\BadRouteException
Code: 0
Message: Cannot register two routes matching "/indexrs51gfe2o2" for method "GET"
File: /www/htdocs/w01ba9c4/xprssn.st/system/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php
Line: 86
Trace

#0 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php(30): FastRoute\DataGenerator\RegexBasedAbstract->addStaticRoute('GET', Array, 'route96')
#1 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/nikic/fast-route/src/RouteCollector.php(44): FastRoute\DataGenerator\RegexBasedAbstract->addRoute('GET', Array, 'route96')
#2 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/Routing/Dispatcher.php(34): FastRoute\RouteCollector->addRoute(Array, '/indexrs51gfe2o...', 'route96')
#3 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/nikic/fast-route/src/functions.php(25): Slim\Routing\Dispatcher->Slim\Routing\{closure}(Object(FastRoute\RouteCollector))
#4 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/Routing/Dispatcher.php(52): FastRoute\simpleDispatcher(Object(Closure), Array)
#5 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/Routing/Dispatcher.php(65): Slim\Routing\Dispatcher->createDispatcher()
#6 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/Routing/RouteResolver.php(46): Slim\Routing\Dispatcher->dispatch('GET', '/tm/plugins')
#7 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(95): Slim\Routing\RouteResolver->computeRoutingResults('/tm/plugins', 'GET')
#8 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(61): Slim\Middleware\RoutingMiddleware->resolveRoutingResultsFromRequest(Object(Slim\Psr7\Request))
#9 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(44): Slim\Middleware\RoutingMiddleware->performRouting(Object(Slim\Psr7\Request))
#10 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Psr7\Request), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#11 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Psr7\Request))
#12 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Psr7\Request), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#13 /www/htdocs/w01ba9c4/xprssn.st/system/typemill/Middleware/SessionMiddleware.php(58): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Psr7\Request))
#14 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Typemill\Middleware\SessionMiddleware->process(Object(Slim\Psr7\Request), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#15 /www/htdocs/w01ba9c4/xprssn.st/system/typemill/Middleware/RemoveCredentialsMiddleware.php(24): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Psr7\Request))
#16 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): Typemill\Middleware\RemoveCredentialsMiddleware->process(Object(Slim\Psr7\Request), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#17 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Psr7\Request))
#18 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/App.php(209): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request))
#19 /www/htdocs/w01ba9c4/xprssn.st/system/vendor/slim/slim/Slim/App.php(193): Slim\App->handle(Object(Slim\Psr7\Request))
#20 /www/htdocs/w01ba9c4/xprssn.st/system/typemill/system.php(455): Slim\App->run()
#21 /www/htdocs/w01ba9c4/xprssn.st/index.php(5): require('/www/htdocs/w01...')
#22 {main}
[Go Back](https://xprssn.st/tm/plugins#)

**Comment by trendschau** [comment]
thank you, that looks like an error in the plugin, I will try to fix that as soon as possible and upload it to the plugin directory

**Comment by trendschau** [comment]
thank you for reporting again, I fixed this error now with versiion 3.1.1: https://plugins.typemill.net/bettersearch

This error only happens if both plugins are activated: search and bettersearch. If you want to use bettersearch, please deactivate the search plugin. If both area actiive, then both plugins won't work correctly.

I hope this helps

**Comment by robs-fotoalbum** [comment]
Thank you for the quick fix and the tip. Works fine now.
