### ISSUE TITLE
Thanks for the Typemill Flat File CMS!!

### ISSUE THREAD

**Issue by AlexL777** [trendschau/typemill#6]
Hi @trendschau ,

I want to thank you for the Typemill CMS, because I discovered it the other day. A passable flat file CMS, which certainly has a future.

I installed such a website at https://typemill.liebrechts-portfolio.de and posted first contents. It looks good and for me as a CMS blogger also easy to handle.

What is the current state of development of this Flat File CMS?

Thanks in Advance.

**Comment by trendschau** [comment]
Hi Alex, 

thank you for using Typemill! The Development of Typemill is still very active, next big steps will be a plugin system (to be released in the next 2 month) and then a authoring system to create and edit content online (planned for summer). 

Best regards

**Comment by AlexL777** [comment]
Hi,
that sounds very exciting and interesting. Anyway, I'll keep track of this CMS and make a great manual or documentation of my portfolio content. Good CMS 👍
