### ISSUE TITLE
Footnotes (and THX for Typemill, Sebastian !)

### ISSUE THREAD

**Issue by carstenwm** [trendschau/typemill#9]
I'm having a problem with footnotes - checked the Markdown syntax, can't seem to find the problem, maybe the issue is known or maybe this n00b just can't read the output here on my [testpage](http://carsten.hedegaard.mobi/interesser/musik)

/Carsten, Denmark

**Comment by trendschau** [comment]
Hi Carsten, 

you are right, this is a bug, the typemill page has the same issue [on the markdown testpage](http://typemill.net/info/markdown-test). I will check it and fix it asap.

Best regards
Sebastian

**Comment by trendschau** [comment]
A small update: I will fix this bug with version 1.1.3, but it still needs one or two weeks. Version 1.1.3 will introduce an admin panel for settings, so it is a bit of work ...

**Comment by carstenwm** [comment]
Vielen Dank - you're moving on, thank you :-) Then I'll transfer some more pages to Typemill - and guess I'll have to learn Twig in order to make changes in the template or make new ones,that will take a while :-D

**Comment by trendschau** [comment]
Hi Carsten,

the bug has been fixed with version 1.1.3 now. It was a bug in the parsedown-library. If you don't want to update to Typemill 1.1.3, then you can update the libraries (e.g. with composer) and the bug should be fixed, too.

Cheers, Sebastian

**Comment by carstenwm** [comment]
:-) Tested and it works - Thank you, Sebastian !
